### ISSUE TITLE
Bouquet should give better indication of bundle landing

### ISSUE THREAD

**Issue by epheph** [DarkFlorist/bouquet#44]

**Comment by MicahZoltu** [comment]
From Discord: https://discord.com/channels/963807285929459772/963807516142235728/1125750975509049415

> there is no indication the transaction was successfully executed and will just show a Stop button but is just stuck there (see screenshot). Only way to check if transaction was executed was by checking Etherscan.

![image](https://github.com/DarkFlorist/bouquet/assets/886059/00c12124-3ece-4089-b06a-bdec0eef2fc7)
